apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ include "ace-validating-webhook.name" . }}-serving-cert
  labels:
    {{- include "ace-validating-webhook.labels" . | nindent 4 }}
  name: {{ include "ace-validating-webhook.name" . }}-service
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    webhook: {{ include "ace-validating-webhook.name" . }}
  type: ClusterIP
